---
- name: Verify Slurmd Service on Ubuntu # This playbook verifies the status of the Slurmd service on Ubuntu hosts.
  hosts: linux # Specifies the target hosts for this play.
  become: true # Enables privilege escalation (become root) for tasks that require it.
  gather_facts: false # Disables gathering facts about the hosts, which can speed up execution if facts are not needed.

  tasks: # Defines the list of tasks to be executed on the target hosts.
    - name: Check Slurmd Service Status # Task to check the status of the 'slurmd' service using the systemd module.
      ansible.builtin.systemd:
        name: slurmd # Specifies the name of the service to manage.
        state: started  # Check if the service is running # Checks if the service is running. If not, it will attempt to start it (or report changed=true if already running).
      register: slurmd_status  # Store the result in a variable # Registers the output of the systemd module into a variable named 'slurmd_status'.

    - name: Display Slurmd Status # Task to display the status of the Slurmd service using the debug module.
      ansible.builtin.debug:
        msg: "Slurmd service is {{ slurmd_status.status.active }}" # Defines the message to display, including the active status from the registered variable.
      when: slurmd_status.changed == false # only show if status check did not change anything # This task only runs if the previous task (checking status) did not make any changes. This typically means the service was already in the 'started' state.

    - name: Fail if Slurmd is not running # Task to fail the playbook execution if the Slurmd service is not reported as 'active'.
      ansible.builtin.fail:
        msg: "Slurmd service is not running!" # Defines the error message to display if the task fails.
      when: slurmd_status.status.active != "active" # changed to use the registered variable # This task only runs if the 'active' status from the registered variable is not equal to "active". This means the service is not running as expected.
